Fix #25.
CollinAlpert/Lombok.NET pull request #27
Opened 2023-06-08 02:15 UTC by View12138

I apologize for not noticing the difference between tabs and spaces. I use Visual Studio and have it set to replace tabs with spaces.

2023-06-26 09:18 UTC, CollinAlpert requested changes

2023-06-26 09:18 UTC, CollinAlpert commented on Lombok.NET/ConstructorGenerators/NoArgsConstructorGenerator.cs
> +		return (SyntaxKind.PublicKeyword, SyntaxFactory.ParameterList(), SyntaxFactory.Block());
Currently the constructor uses the type's modifier and it should stay that way, otherwise it will be a breaking change.

2023-06-26 09:18 UTC, CollinAlpert commented on Lombok.NET/SourceGeneratorAttributes.cs
> +public enum ModifierType
Why the new enum? Can't we use `AccessTypes` and when it is omitted, we default to the current behavior (which would be WithClass in your new enum).

2023-06-27 02:38 UTC, View12138 commented on Lombok.NET/ConstructorGenerators/NoArgsConstructorGenerator.cs
> +		return (SyntaxKind.PublicKeyword, SyntaxFactory.ParameterList(), SyntaxFactory.Block());
Oh,I didn't notice this, you are right. I will fix this in the new PR.

2023-06-27 02:38 UTC, View12138 commented on Lombok.NET/SourceGeneratorAttributes.cs
> +public enum ModifierType
I think `AccessType` is Flags enum. but the constructor can only have one modifier. so I used a new enum.

2023-06-27 02:39 UTC, closed without merging

2023-06-27 15:16 UTC, CollinAlpert commented on Lombok.NET/ConstructorGenerators/NoArgsConstructorGenerator.cs
> +		return (SyntaxKind.PublicKeyword, SyntaxFactory.ParameterList(), SyntaxFactory.Block());
You can just fix stuff in the current PR, you don't need to open a new PR every time.

2023-06-27 15:24 UTC, CollinAlpert commented on Lombok.NET/SourceGeneratorAttributes.cs
> +public enum ModifierType
No, a constructor can also be `protected internal` or `private protected` just like a type.