Feat: #38
CollinAlpert/Lombok.NET pull request #39
Opened 2024-02-23 10:12 UTC by View12138

2024-02-24 13:13 UTC, CollinAlpert commented
Thanks for this, it's a good idea! Can you make sure the tests pass before I review the PR?

2024-02-24 16:29 UTC, View12138 commented
I'm sure that the PR code can pass the test, because I can't run your test project locally, so I wrote another test project myself to test the code I submitted, and the new code in the issue is generated by my local test project

2024-02-24 16:37 UTC, View12138 commented
I'd also like to share with you my test scenario, which can be used to get into debug mode using VS's debug test method without having to attach to a process, which I think might be easier to write code and test projects

2024-02-26 10:39 UTC, CollinAlpert requested changes

2024-02-26 10:39 UTC, CollinAlpert commented on Lombok.NET/ConstructorGenerators/RequiredArgsConstructorGenerator.cs
> +					var fields = typeDeclaration.Members
These seem to be only whitespace changes, please revert.

2024-02-26 10:40 UTC, CollinAlpert commented
Please let me know why you can't run the test project locally, this is something I would definitely need to fix.

2024-02-27 02:02 UTC, View12138 commented on Lombok.NET/ConstructorGenerators/RequiredArgsConstructorGenerator.cs
> +					var fields = typeDeclaration.Members
I've already fixed it.

2024-02-27 05:36 UTC, View12138 commented
This is my [test project](https://github.com/View12138/Lombok.NET/blob/view-test-project/Lombok.NET.Tests/ConstructorGeneratorsTests.cs)

2024-03-06 22:50 UTC, CollinAlpert commented
Sorry about the delay, I've had a busy week but will get to this on the weekend the latest.

2024-03-11 19:07 UTC, CollinAlpert commented
Looks good! I will look into using [Verify](https://github.com/VerifyTests/Verify) for tests in the future.

2024-03-11 19:08 UTC, merged